---
engines:
  csslint:
    enabled: true
    exclude_paths:
      - "client/public/*"
  duplication:
    exclude_paths:
      - "client/public/*"
      - "public/webssh2.bundle.js"
      - "workspace/*"
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- node_modules/
- "public/webssh2.bundle.js"
- "workspace/*"


