version: '3'

services:
  mywebssh:
    image: node:slim
    tty: true
    restart: always
    container_name: web_ssh
    volumes:
      - ./:/app
    ports:
    - 2222:2222
    working_dir: /app
    entrypoint:
    - /bin/sh
    - ./run.sh
